---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-reader-deployment
  labels:
    app: rss-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rss-reader
  template:
    metadata:
      labels:
        app: rss-reader
    spec:
      containers:
      - name: app
        image: jmarhee/rss-freeipad-reader:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8888"
        - name: SITE_NAME
          value: {{ .Values.sitename }}
        - name: FEED_YAML_PATH
          value: {{ .Values.feedpath }}
        volumeMounts:
        - name: feeds
          mountPath: {{ .Values.configpath }}
          readOnly: false
{{ if eq .Values.filebrower "enabled" }}
      - name: app-filebrowser
        image: hurlenko/filebrowser
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: FB_BASEURL
          value: "/browser"
        volumeMounts:
        - name: feeds
          mountPath: "/data"
          readOnly: false
{{ end }}
      volumes:
      - name: feeds
        persistentVolumeClaim:
          claimName: rss-reader-pv-claim
