apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rss-reader-ingress
spec:
  rules:
    - host: "{{ .Values.fqdn }}"
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name:  rss-reader-service
                port:
                  number: 80