apiVersion: v1
kind: Service
metadata:
  name: rss-reader-service
spec:
  selector:
    app: rss-reader
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
      name: "http-app"
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: "http-filebrowser"
        